name: angular_pindicator

version: 0.1.0
author: Mike Mitterer  <office@mikemitterer.at>
description: Sample for Angular-Component

environment:
  sdk: '>=1.3.0 <2.0.0'

dependencies:
  browser: any

  validate: any
  console_log_handler: any

  angular: ">=1.0.0 <2.0.0"


transformers:
- angular